steps:
  # Connect to Cloud Shell
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth login  # Authenticate with Google Cloud (if not already logged in)
        gcloud config set project devproje1  # Replace with your Google Cloud project ID
          # Replace with your desired compute zone

  # Connect to GKE Cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials dev-task-cluster-dev --region=us-central1-c  # Replace with your GKE cluster details

  # Clone Git Repo
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - 'https://github.com/urolimevishnu/devtask2.git'
      - 'wordpress'  # Directory where your Helm chart files are located

  # Install Helm Chart
  - name: 'gcr.io/cloud-builders/helm'
    args:
      - 'upgrade'
      - '--install'
      - 'YOUR_HELM_RELEASE_NAME'
      - 'wordpress'
      # Add any other Helm upgrade/install flags as needed

  # Verify Deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'get'
      - 'pods'
      - '--namespace=wordpress'  # Replace with your target namespace

timeout: '1800s'  # Set a timeout that fits your deployment's duration
