steps:
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade', '--install', 'wordpress', './wordpress', '--namespace', 'wordpress', '--create-namespace']
  
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=dev-task-cluster-dev'
