apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentVolumeMysql.storageCapacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/shared/mysql-data'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentVolumeWordpress.storageCapacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/shared/wp-data'
